export const products = 
     [
    {   id: 1,
        name: 'Lipgloss Cristal',
        type:'Limited-Edition',
        describe: 'Gloss Bomb universal lip luminizer',
        price: '€ 39,00',
        tax: '(inclusive 21%)' ,
        stock: '70',
        defaultImage: ["src/assets/images/gloss/lipgloss - cristal.jpg"],
        hoverImage: ["src/assets/images/gloss/close/lipgloss - cristal - close.jpg"],
        image:["src/assets/images/gloss/lipgloss - cristal.jpg"]
    },

    {   id: 2,
        name: 'Lipgloss Champagne',
        type:'Limited-Edition',
        describe: 'Gloss Bomb universal lip luminizer',
        price: '€ 39,00',
        tax: '(inclusive 21%)',
        stock: '98',
        defaultImage: ["src/assets/images/gloss/lipgloss - champ.jpg"],
        hoverImage: ["src/assets/images/gloss/close/lipgloss - champ - close.jpg"],
        image:["src/assets/images/gloss/lipgloss - champ.jpg"]
    },
    {   id: 3,
        name: 'Lipgloss Coldheart',
        type:'Limited-Edition',
        describe: 'Gloss Bomb universal lip luminizer',
        price: '€ 39,00',
        tax: '(inclusive 21%)',
        stock: '106',
        defaultImage: ["src/assets/images/gloss/lipgloss - coldheart .jpg"],
        hoverImage: ["src/assets/images/gloss/close/lipgloss - coldheart - close.jpg"],
        image:["src/assets/images/gloss/lipgloss - coldheart .jpg"]

    },
    {   id: 4,
        name: 'Lipgloss FentyGlow',
        type:'Cream',
        describe: 'GLOSS BOMB CREAM COLOR DRIP LIP CREAM',
        price: '€ 27,00',
        tax: '(inclusive 21%)',
        stock: '115',
        defaultImage: ["src/assets/images/gloss cream/lipgloss - fentyglow.jpg"],
        hoverImage: ["src/assets/images/gloss cream/close/lipgloss - fentyglow - close.jpg"],
        image:["src/assets/images/gloss cream/lipgloss - fentyglow.jpg"]
    },
    {   id: 5,
        name: 'Lipgloss Honey',
        type:'Cream',
        describe: 'GLOSS BOMB CREAM COLOR DRIP LIP CREAM',
        price: '€ 27,00',
        tax: '(inclusive 21%)',
        stock: '120',
        defaultImage: ["src/assets/images/gloss cream/lipgloss - honey.jpg"],
        hoverImage: ["src/assets/images/gloss cream/close/lipgloss - honey - close.jpg"],
        image:["src/assets/images/gloss cream/lipgloss - honey.jpg"]
    },
    {   id: 6,
        name: 'Lipgloss Berry',
        type:'Cream',
        describe: 'GLOSS BOMB CREAM COLOR DRIP LIP CREAM',
        price: '€ 27,00',
        tax: 'inclusive 21%',
        stock: '135',
        defaultImage: ["src/assets/images/gloss cream/lipgloss - berry.jpg"],
        hoverImage: ["src/assets/images/gloss cream/close/lipgloss - berry - close.jpg"],
        image:["src/assets/images/gloss cream/lipgloss - berry.jpg"]
    },
    {   id: 7,
        name: 'Lipgloss Cookie',
        type:'Cream',
        describe: 'GLOSS BOMB CREAM COLOR DRIP LIP CREAM',
        price: '€ 27,00',
        tax: 'inclusive 21%',
        stock: '125',
        defaultImage: ["src/assets/images/gloss cream/lipgloss - cookie .jpg"],
        hoverImage: ["src/assets/images/gloss cream/close/lipgloss - cookie - close.jpg"],
        image:["src/assets/images/gloss cream/lipgloss - cookie .jpg"]
    },
    {   id: 8,
        name: 'Lipgloss Mauves',
        type:'Cream',
        describe: 'GLOSS BOMB CREAM COLOR DRIP LIP CREAM',
        price: '€ 27,00',
        tax: 'inclusive 21%',
        stock: '123',
        defaultImage: ["src/assets/images/gloss cream/lipgloss- mauves.jpg"],
        hoverImage: ["src/assets/images/gloss cream/close/lipgloss - mauves - close.jpg"],
        image:["src/assets/images/gloss cream/lipgloss- mauves.jpg"]
    },
    {   id: 9,
        name: 'Lipgloss Clear',
        type:'Heat',
        describe: 'GLOSS BOMB HEAT UNIVERSAL LIP LUMINIZER + PLUMPER',
        price: '€ 32,00',
        tax: 'inclusive 21%',
        stock: '127',
        defaultImage: ["src/assets/images/gloss heat/lipgloss - clear.jpg"],
        hoverImage: ["src/assets/images/gloss heat/close/lipgloss - close - clear.jpg"],
        image:["src/assets/images/gloss heat/lipgloss - clear.jpg"]
    },
    {   id: 10,
        name: 'Lipgloss Fu$$y',
        type:'Heat',
        describe: 'GLOSS BOMB HEAT UNIVERSAL LIP LUMINIZER + PLUMPER',
        price: '€ 32,00',
        tax: 'inclusive 21%',
        stock: '110',
        defaultImage: ["src/assets/images/gloss heat/lipgloss - fu$$y.jpg"],
        hoverImage: ["src/assets/images/gloss heat/close/lipgloss - clear - fu$$y.jpg"],
        image:["src/assets/images/gloss heat/lipgloss - fu$$y.jpg"]
    },
    {   id: 11,
        name: 'Lipgloss Glow',
        type:'Heat',
        describe: 'GLOSS BOMB HEAT UNIVERSAL LIP LUMINIZER + PLUMPER',
        price: '€ 32,00',
        tax: 'inclusive 21%',
        stock: '93',
        defaultImage: ["src/assets/images/gloss heat/lipgloss - glow heat.jpg"],
        hoverImage: ["src/assets/images/gloss heat/close/lipgloss - close - glow.jpg"],
        image:["src/assets/images/gloss heat/lipgloss - glow heat.jpg"]
    },
    {   id: 12,
        name: 'Lipgloss Hot Cherry',
        type:'Heat',
        describe: 'GLOSS BOMB HEAT UNIVERSAL LIP LUMINIZER + PLUMPER',
        price: '€ 32,00',
        tax: 'inclusive 21%',
        stock: '28',
        defaultImage: ["src/assets/images/gloss heat/lipgloss - hot cherry.jpg"],
        hoverImage: ["src/assets/images/gloss heat/close/lipgloss - close - hot cherry.jpg"],
        image:["src/assets/images/gloss heat/lipgloss - hot cherry.jpg"]
    },
    {   id: 13,
        name: 'Lipgloss Hot Chocolit',
        type:'Heat',
        describe: 'GLOSS BOMB HEAT UNIVERSAL LIP LUMINIZER + PLUMPER',
        price: '€ 32,00',
        tax: 'inclusive 21%',
        stock: '56',
        defaultImage: ["src/assets/images/gloss heat/lipgloss - hot chocolit heat.jpg"],
        hoverImage: ["src/assets/images/gloss heat/close/lipgloss - close - hot chocolit heat.jpg"],
        image:["src/assets/images/gloss heat/lipgloss - hot chocolit heat.jpg"]
    },
    {   id: 14,
        name: 'Lipgloss Lemon',
        type:'Heat',
        describe: 'GLOSS BOMB HEAT UNIVERSAL LIP LUMINIZER + PLUMPER',
        price: '€ 32,00',
        tax: 'inclusive 21%',
        stock: '76',
        defaultImage: ["src/assets/images/gloss heat/lipgloss - lemon heat.jpg"],
        hoverImage: ["src/assets/images/gloss heat/close/lipgloss - close - lemon heat.jpg"],
        image:["src/assets/images/gloss heat/lipgloss - lemon heat.jpg"]
    },
    {   id: 15,
        name: 'Lipstick Retro Rose',
        type:'Shiny',
        describe: 'SLIP SHINE SHEER SHINY LIPSTICK',
        price: '€ 29,00',
        tax: 'inclusive 21%',
        stock: '55',
        defaultImage: ["src/assets/images/lipstick/Lipstick - Retro Rose.jpg"],
        hoverImage: ["src/assets/images/lipstick/close/Lipstick - close - Retro Rose.jpg"],
        image:["src/assets/images/lipstick/Lipstick - Retro Rose.jpg"]
    },
    {   id: 16,
        name: 'Lipstick Glazed',
        type:'Shiny',
        describe: 'SLIP SHINE SHEER SHINY LIPSTICK',
        price: '€ 29,00',
        tax: 'inclusive 21%',
        stock: '46',
        defaultImage: ["src/assets/images/lipstick/Lipstick - Glazed.jpg"],
        hoverImage: ["src/assets/images/lipstick/close/Lipstick - close - Glazed.jpg"],
        image:["src/assets/images/lipstick/Lipstick - Glazed.jpg"]
    },
    {   id: 17,
        name: 'Lipstick Goji Gang',
        type:'Shiny',
        describe: 'SLIP SHINE SHEER SHINY LIPSTICK',
        price: '€ 29,00',
        tax: 'inclusive 21%',
        stock: '98',
        defaultImage: ["src/assets/images/lipstick/Lipstick - Goji Gang.jpg"],
        hoverImage: ["src/assets/images/lipstick/close/Lipstick - close - Goji Gang.jpg"],
        image:["src/assets/images/lipstick/Lipstick - Goji Gang.jpg"]
    },
    {   id: 18,
        name: 'Lipstick Cookie & Cocoa',
        type:'Shiny',
        describe: 'SLIP SHINE SHEER SHINY LIPSTICK',
        price: '€ 29,00',
        tax: 'inclusive 21%',
        stock: '57',
        defaultImage: ["src/assets/images/lipstick/Lipstick - Cookies & Cocoa.jpg"],
        hoverImage: ["src/assets/images/lipstick/close/Lipstick - close - Cookies & Cocoa.jpg"],
        image:["src/assets/images/lipstick/Lipstick - Cookies & Cocoa.jpg"]
    },
    {   id: 19,
        name: 'Lipstick Bubble Rum',
        type:'Shiny',
        describe: 'SLIP SHINE SHEER SHINY LIPSTICK',
        price: '€ 29,00',
        tax: 'inclusive 21%',
        stock: '89',
        defaultImage: ["src/assets/images/lipstick/Lipstick - Bubble Rum.jpg"],
        hoverImage: ["src/assets/images/lipstick/close/Lipstick - close - Bubble Rum.jpg"],
        image:["src/assets/images/lipstick/Lipstick - Bubble Rum.jpg"]
    },
    {   id: 20,
        name: 'Lipstick Vamps Who Brunch',
        type:'Shiny',
        describe: 'SLIP SHINE SHEER SHINY LIPSTICK',
        price: '€ 29,00',
        tax: 'inclusive 21%',
        stock: '69',
        defaultImage: ["src/assets/images/lipstick/Lipstick - Vamps Who Brunch.jpg"],
        hoverImage: ["src/assets/images/lipstick/close/Lipstick - close - Vamps Who - Brunch .jpg"],
        image:["src/assets/images/lipstick/Lipstick - Vamps Who Brunch.jpg"]
    },
    
    ]
  